import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/Sidebar";
import UserProvider from "@/provider/UserProvider";
import SupabaseProvider from "@/provider/SupabaseProvider";
import ToastProvider from "@/provider/ToastProvider";
import Player from "@/components/Player";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import ModalProvier from "@/provider/ModalProvider";

const notoSans = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <ToastProvider />
        <SupabaseProvider>
          <ReactQueryProvider>
            <UserProvider>
              <ModalProvier />
              <Sidebar>{children}</Sidebar>
              <Player />
            </UserProvider>
          </ReactQueryProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
